"""Synthetic snapshot companies: payloads and respx route setup.

Everything here is fictional. Three snapshot cases share this module:

- AMBER (tests/fixtures/amber/): GILDED ANVIL HOLDINGS LTD, the weekend 2
  planted-signal company (accounts overdue, wholesale churn, one
  outstanding charge, a sub-threshold sanctions near-match at 0.55 against
  threshold 0.7, three media items, one with vocabulary that must never
  reach a memo). No deck, no site: the claims-free AMBER preserved from
  weekend 2.
- GOLDEN (tests/fixtures/golden/): FABRICATED WIDGETS LTD (the conftest
  fixture company) screened WITH the committed fixture deck. The deck
  plants the golden contradictions (operating-since before incorporation,
  debt-free against the outstanding charge), so R4 fires and the case is
  RED. Its registry routes live in tests/conftest.py.
- GREEN (tests/fixtures/green/): PLACID MERIDIAN CONSULTING LTD, clean
  everywhere, screened WITH a fictional website whose about page supports
  its one checkable claim. Stays GREEN with a supported claim.

The committed fixtures are generated by running the real CLI against these
routes with a frozen clock; tests replay the same routes, so fixture drift
shows up as a diff.
"""

from __future__ import annotations

import json
from typing import Any

import httpx
import respx

BASE_URL = "https://api.company-information.service.gov.uk"
OPENSANCTIONS_URL = "https://api.opensanctions.org"
TAVILY_URL = "https://api.tavily.com/search"

AMBER_NUMBER = "99999901"
AMBER_NAME = "GILDED ANVIL HOLDINGS LTD"
AMBER_PREVIOUS_NAME = "AURUM ANVIL LTD"
GREEN_NUMBER = "99999902"
GREEN_NAME = "PLACID MERIDIAN CONSULTING LTD"
GREEN_SITE_URL = "https://placid-meridian.example"

SANCTIONS_TEST_KEY = "fixture-opensanctions-key-not-real"
TAVILY_TEST_KEY = "tvly-fixture-key-not-real"

# The amber media titles. The first one contains vocabulary the memo
# language gate bans; it must appear in evidence and synthesis input but
# never in a rendered memo.
AMBER_MEDIA_ITEMS: list[dict[str, str]] = [
    {
        "title": "Gilded Anvil Holdings faces fraud inquiry by trade body",
        "url": "https://fictional-gazette.example/business/gilded-anvil-inquiry",
        "published_date": "2026-05-14",
        "content": "A fictional trade body opened an inquiry into the company.",
        "category": "misconduct",
    },
    {
        "title": "Regulator reviews late filings at Gilded Anvil",
        "url": "https://made-up-times.example/markets/gilded-anvil-filings",
        "published_date": "2026-07-21",
        "content": "A fictional regulator asked about overdue accounts.",
        "category": "regulatory",
    },
    {
        "title": "Supplier files claim against Gilded Anvil Holdings",
        "url": "https://examiner-fictional.example/law/gilded-anvil-claim",
        "published_date": "2026-06-02",
        "content": "A fictional supplier filed a claim over unpaid invoices.",
        "category": "litigation",
    },
]


def amber_profile() -> dict[str, Any]:
    return {
        "company_name": AMBER_NAME,
        "company_number": AMBER_NUMBER,
        "company_status": "active",
        "date_of_creation": "2021-04-01",
        "type": "ltd",
        "jurisdiction": "england-wales",
        "sic_codes": ["24540"],
        "registered_office_address": {
            "address_line_1": "7 Invented Foundry Row",
            "locality": "Faketown",
            "postal_code": "ZZ98 8ZZ",
            "country": "England",
        },
        "previous_company_names": [
            {
                "name": AMBER_PREVIOUS_NAME,
                "effective_from": "2021-04-01",
                "ceased_on": "2023-09-01",
            }
        ],
        "accounts": {
            "next_accounts": {
                "overdue": True,
                "due_on": "2026-01-31",
                "period_end_on": "2025-04-30",
            }
        },
        "confirmation_statement": {"overdue": False, "next_due": "2026-10-15"},
        "links": {
            "self": f"/company/{AMBER_NUMBER}",
            "officers": f"/company/{AMBER_NUMBER}/officers",
            "filing_history": f"/company/{AMBER_NUMBER}/filing-history",
            "persons_with_significant_control": (
                f"/company/{AMBER_NUMBER}/persons-with-significant-control"
            ),
            "charges": f"/company/{AMBER_NUMBER}/charges",
        },
    }


def amber_officers() -> dict[str, Any]:
    return {
        "active_count": 2,
        "resigned_count": 3,
        "total_results": 5,
        "items": [
            {
                "name": "ANVIL, Arabella",
                "officer_role": "director",
                "appointed_on": "2021-04-01",
                "nationality": "British",
                "date_of_birth": {"month": 3, "year": 1979},
                "links": {"officer": {"appointments": "/officers/fictGold001/appointments"}},
            },
            {
                "name": "FORGE, Fitzwilliam",
                "officer_role": "director",
                "appointed_on": "2021-04-01",
                "nationality": "British",
                "date_of_birth": {"month": 11, "year": 1985},
                "links": {"officer": {"appointments": "/officers/fictGold002/appointments"}},
            },
            {
                "name": "TONGS, Tabitha",
                "officer_role": "director",
                "appointed_on": "2021-04-01",
                "resigned_on": "2026-01-10",
                "date_of_birth": {"month": 5, "year": 1981},
                "links": {"officer": {"appointments": "/officers/fictGold003/appointments"}},
            },
            {
                "name": "BELLOWS, Barnaby",
                "officer_role": "director",
                "appointed_on": "2022-01-05",
                "resigned_on": "2026-03-22",
                "date_of_birth": {"month": 8, "year": 1990},
                "links": {"officer": {"appointments": "/officers/fictGold004/appointments"}},
            },
            {
                "name": "CRUCIBLE, Cressida",
                "officer_role": "secretary",
                "appointed_on": "2021-04-01",
                "resigned_on": "2026-06-30",
                "links": {"officer": {"appointments": "/officers/fictGold005/appointments"}},
            },
        ],
    }


def amber_psc() -> dict[str, Any]:
    return {
        "total_results": 1,
        "active_count": 1,
        "ceased_count": 0,
        "items": [
            {
                "name": "Mrs Arabella Anvil",
                "kind": "individual-person-with-significant-control",
                "natures_of_control": ["ownership-of-shares-75-to-100-percent"],
                "notified_on": "2021-04-01",
                "nationality": "British",
                "date_of_birth": {"month": 3, "year": 1979},
            }
        ],
    }


def amber_filing_history() -> dict[str, Any]:
    return {
        "total_count": 4,
        "filing_history_status": "filing-history-available",
        "items": [
            {
                "transaction_id": "FICT0001",
                "category": "accounts",
                "type": "AA",
                "date": "2025-01-20",
                "description": "accounts-with-accounts-type-micro-entity",
            },
            {
                "transaction_id": "FICT0002",
                "category": "confirmation-statement",
                "type": "CS01",
                "date": "2025-10-02",
                "description": "confirmation-statement-with-no-updates",
            },
            {
                "transaction_id": "FICT0003",
                "category": "mortgage",
                "type": "MR01",
                "date": "2024-05-03",
                "description": "mortgage-create-with-deed",
            },
            {
                "transaction_id": "FICT0004",
                "category": "change-of-name",
                "type": "NM01",
                "date": "2023-09-01",
                "description": "change-of-name",
            },
        ],
    }


def amber_charges() -> dict[str, Any]:
    return {
        "total_count": 1,
        "satisfied_count": 0,
        "part_satisfied_count": 0,
        "items": [
            {
                "charge_code": "999999010001",
                "status": "outstanding",
                "created_on": "2024-05-01",
                "delivered_on": "2024-05-03",
                "classification": {
                    "type": "charge-description",
                    "description": "A registered charge",
                },
                "persons_entitled": [{"name": "FICTIONAL CAPITAL PARTNERS LLP"}],
            }
        ],
    }


def _appointments(name: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "total_results": len(items),
        "items_per_page": 100,
        "start_index": 0,
        "name": name,
        "items": items,
    }


def _appointment(
    name: str, company_name: str, company_number: str, resigned_on: str | None = None
) -> dict[str, Any]:
    item: dict[str, Any] = {
        "name": name,
        "officer_role": "director",
        "appointed_on": "2021-04-01",
        "appointed_to": {
            "company_name": company_name,
            "company_number": company_number,
            "company_status": "active",
        },
        "links": {"company": f"/company/{company_number}"},
    }
    if resigned_on:
        item["resigned_on"] = resigned_on
    return item


def empty_disqualified_search() -> dict[str, Any]:
    return {
        "total_results": 0,
        "items_per_page": 20,
        "start_index": 0,
        "kind": "search#disqualified-officers",
        "items": [],
    }


def amber_sanctions_response() -> dict[str, Any]:
    """Batch /match response: q001 company near-miss at 0.55, rest empty.

    Three queries: the company, ANVIL Arabella (screened once as officer
    and PSC), and FORGE Fitzwilliam.
    """
    return {
        "responses": {
            "q001": {
                "status": 200,
                "results": [
                    {
                        "id": "fict-entity-001",
                        "caption": "Gilded Anvil Trading FZE",
                        "schema": "Company",
                        "datasets": ["fict_sanctions_list"],
                        "score": 0.55,
                        "match": False,
                        "features": {"name_similarity": 0.61},
                    }
                ],
                "total": {"value": 1, "relation": "eq"},
            },
            "q002": {"status": 200, "results": [], "total": {"value": 0, "relation": "eq"}},
            "q003": {"status": 200, "results": [], "total": {"value": 0, "relation": "eq"}},
        },
        "limit": 5,
    }


def amber_tavily_responder(request: httpx.Request) -> httpx.Response:
    """Per-query Tavily payloads: three planted items, everything else empty."""
    body = json.loads(request.content.decode("utf-8"))
    query = body.get("query", "")
    results: list[dict[str, str]] = []
    if query == f'"{AMBER_NAME}" fraud':
        results = [_tavily_result(AMBER_MEDIA_ITEMS[0])]
    elif query == f'"{AMBER_NAME}" regulator':
        results = [_tavily_result(AMBER_MEDIA_ITEMS[1])]
    elif query == f'"{AMBER_NAME}" lawsuit':
        results = [_tavily_result(AMBER_MEDIA_ITEMS[2])]
    return httpx.Response(
        200,
        json={
            "query": query,
            "results": results,
            "response_time": 0.01,
        },
    )


def _tavily_result(item: dict[str, str]) -> dict[str, Any]:
    return {
        "title": item["title"],
        "url": item["url"],
        "content": item["content"],
        "score": 0.9,
        "published_date": item["published_date"],
    }


def empty_tavily_responder(request: httpx.Request) -> httpx.Response:
    body = json.loads(request.content.decode("utf-8"))
    return httpx.Response(
        200, json={"query": body.get("query", ""), "results": [], "response_time": 0.01}
    )


def register_amber_routes(router: respx.MockRouter) -> None:
    """Every route one amber `screen 99999901` needs, fully offline."""
    profile_url = f"{BASE_URL}/company/{AMBER_NUMBER}"
    router.get(profile_url).respond(200, json=amber_profile())
    router.get(f"{profile_url}/officers").respond(200, json=amber_officers())
    router.get(f"{profile_url}/persons-with-significant-control").respond(200, json=amber_psc())
    router.get(f"{profile_url}/filing-history").respond(200, json=amber_filing_history())
    router.get(f"{profile_url}/charges").respond(200, json=amber_charges())
    router.get(f"{BASE_URL}/officers/fictGold001/appointments").respond(
        200,
        json=_appointments(
            "ANVIL, Arabella",
            [
                _appointment("ANVIL, Arabella", AMBER_NAME, AMBER_NUMBER),
                _appointment("ANVIL, Arabella", "AURUM SMELTING LTD", "99999803"),
            ],
        ),
    )
    router.get(f"{BASE_URL}/officers/fictGold002/appointments").respond(
        200,
        json=_appointments(
            "FORGE, Fitzwilliam",
            [_appointment("FORGE, Fitzwilliam", AMBER_NAME, AMBER_NUMBER)],
        ),
    )
    router.get(f"{BASE_URL}/search/disqualified-officers").respond(
        200, json=empty_disqualified_search()
    )
    router.post(f"{OPENSANCTIONS_URL}/match/default").respond(200, json=amber_sanctions_response())
    router.post(TAVILY_URL).mock(side_effect=amber_tavily_responder)


def green_profile() -> dict[str, Any]:
    return {
        "company_name": GREEN_NAME,
        "company_number": GREEN_NUMBER,
        "company_status": "active",
        "date_of_creation": "2018-06-15",
        "type": "ltd",
        "jurisdiction": "england-wales",
        "sic_codes": ["70229"],
        "registered_office_address": {
            "address_line_1": "12 Nonexistent Crescent",
            "locality": "Faketown",
            "postal_code": "ZZ97 7ZZ",
            "country": "England",
        },
        "accounts": {
            "next_accounts": {"overdue": False, "due_on": "2027-03-31"},
            "last_accounts": {"made_up_to": "2025-06-30", "type": "small"},
        },
        "confirmation_statement": {"overdue": False, "next_due": "2027-06-29"},
        "links": {
            "self": f"/company/{GREEN_NUMBER}",
            "officers": f"/company/{GREEN_NUMBER}/officers",
            "filing_history": f"/company/{GREEN_NUMBER}/filing-history",
            "persons_with_significant_control": (
                f"/company/{GREEN_NUMBER}/persons-with-significant-control"
            ),
        },
    }


def green_officers() -> dict[str, Any]:
    return {
        "active_count": 1,
        "resigned_count": 0,
        "total_results": 1,
        "items": [
            {
                "name": "MERIDIAN, Mabel",
                "officer_role": "director",
                "appointed_on": "2018-06-15",
                "nationality": "British",
                "date_of_birth": {"month": 7, "year": 1976},
                "links": {"officer": {"appointments": "/officers/fictGreen001/appointments"}},
            }
        ],
    }


def green_psc() -> dict[str, Any]:
    return {
        "total_results": 1,
        "active_count": 1,
        "ceased_count": 0,
        "items": [
            {
                "name": "Ms Mabel Meridian",
                "kind": "individual-person-with-significant-control",
                "natures_of_control": ["ownership-of-shares-75-to-100-percent"],
                "notified_on": "2018-06-15",
                "nationality": "British",
                "date_of_birth": {"month": 7, "year": 1976},
            }
        ],
    }


def green_filing_history() -> dict[str, Any]:
    return {
        "total_count": 2,
        "filing_history_status": "filing-history-available",
        "items": [
            {
                "transaction_id": "FICT0101",
                "category": "accounts",
                "type": "AA",
                "date": "2025-09-12",
                "description": "accounts-with-accounts-type-small",
            },
            {
                "transaction_id": "FICT0102",
                "category": "confirmation-statement",
                "type": "CS01",
                "date": "2025-06-29",
                "description": "confirmation-statement-with-no-updates",
            },
        ],
    }


def green_sanctions_response() -> dict[str, Any]:
    """Both subjects (the company, and the director who is also the PSC)
    come back with zero candidates."""
    empty = {"status": 200, "results": [], "total": {"value": 0, "relation": "eq"}}
    return {"responses": {"q001": empty, "q002": empty}, "limit": 5}


GREEN_ROBOTS_TXT = "User-agent: *\nDisallow: /private\n"

GREEN_SITE_HOME_HTML = """<!DOCTYPE html>
<html>
<head><title>Placid Meridian Consulting</title>
<style>body { color: #222; }</style>
<script>console.log("never extracted");</script>
</head>
<body>
<header><span>Placid Meridian Consulting Ltd</span></header>
<nav><a href="/">Home</a> <a href="/about">About us</a> <a href="/private/notes">Private</a></nav>
<main>
<h1>Placid Meridian Consulting</h1>
<p>Calm, dependable advice for ambitious teams.</p>
<p>We work with founders across the country on planning and governance.</p>
</main>
<footer>Registered in England. Entirely fictional.</footer>
</body>
</html>
"""

GREEN_SITE_ABOUT_HTML = """<!DOCTYPE html>
<html>
<head><title>About us</title></head>
<body>
<nav><a href="/">Home</a> <a href="/about">About us</a></nav>
<main>
<h1>About us</h1>
<p>Founded in 2018 by Mabel Meridian.</p>
<p>We advise fictional companies on entirely imaginary matters.</p>
</main>
<footer>Registered in England. Entirely fictional.</footer>
</body>
</html>
"""


def register_green_site_routes(router: respx.MockRouter) -> None:
    """The fictional green company website: robots, homepage, about page."""
    router.get(f"{GREEN_SITE_URL}/robots.txt").respond(
        200, text=GREEN_ROBOTS_TXT, headers={"content-type": "text/plain"}
    )
    router.get(f"{GREEN_SITE_URL}/").respond(
        200, text=GREEN_SITE_HOME_HTML, headers={"content-type": "text/html"}
    )
    router.get(f"{GREEN_SITE_URL}/about").respond(
        200, text=GREEN_SITE_ABOUT_HTML, headers={"content-type": "text/html"}
    )


def register_green_routes(router: respx.MockRouter) -> None:
    """Every route one green `screen 99999902 --site ...` needs, offline."""
    profile_url = f"{BASE_URL}/company/{GREEN_NUMBER}"
    router.get(profile_url).respond(200, json=green_profile())
    router.get(f"{profile_url}/officers").respond(200, json=green_officers())
    router.get(f"{profile_url}/persons-with-significant-control").respond(200, json=green_psc())
    router.get(f"{profile_url}/filing-history").respond(200, json=green_filing_history())
    router.get(f"{BASE_URL}/officers/fictGreen001/appointments").respond(
        200,
        json=_appointments(
            "MERIDIAN, Mabel",
            [_appointment("MERIDIAN, Mabel", GREEN_NAME, GREEN_NUMBER)],
        ),
    )
    router.get(f"{BASE_URL}/search/disqualified-officers").respond(
        200, json=empty_disqualified_search()
    )
    router.post(f"{OPENSANCTIONS_URL}/match/default").respond(200, json=green_sanctions_response())
    router.post(TAVILY_URL).mock(side_effect=empty_tavily_responder)
    register_green_site_routes(router)
