"""Snapshot cases: amber (claims-free), golden (RED via claims), green.

Three committed fixture cases, all generated by running the real CLI
against the synthetic routes with a frozen clock:

- amber/: GILDED ANVIL HOLDINGS LTD without deck or site. The weekend 2
  claims-free AMBER, preserved. casefile.json is the deterministic screen
  output; the memo snapshot is rendered through the canned fake provider.
- golden/: FABRICATED WIDGETS LTD screened WITH the committed fixture deck
  through a canned model over mocked transport. The deck plants an
  operating-since year before incorporation and a debt-free claim against
  the outstanding charge, so R4 fires: the RED case. casefile.json and
  memo.md are the full final CLI outputs, byte-compared on replay.
- green/: PLACID MERIDIAN CONSULTING LTD screened WITH its fictional site;
  its checkable claim is supported and the verdict stays GREEN.

The replay tests re-run the full pipeline and require byte-identical
output, so any behavior drift in the stages shows up as a fixture diff,
not silence.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import httpx
import pytest
import respx
from typer.testing import CliRunner

from coldscreen.casedir import load_casefile
from coldscreen.cli import app
from coldscreen.language import find_banned_terms
from coldscreen.models import CaseFile
from coldscreen.render import render_memo
from coldscreen.rubric import detect_candidates
from coldscreen.synthesis import (
    SynthesisResult,
    apply_synthesis,
    build_synthesis_input,
    synthesize,
)

from . import synthetic
from .conftest import FIXTURES_DIR, mock_company_routes
from .fakes import FakeModelProvider, assessment_json, synthesis_json

AMBER_DIR = FIXTURES_DIR / "amber"
GOLDEN_DIR = FIXTURES_DIR / "golden"
GREEN_DIR = FIXTURES_DIR / "green"
DECK_PATH = FIXTURES_DIR / "deck_fabricated_widgets.pdf"
OLLAMA_CHAT_URL = "http://localhost:11434/api/chat"

runner = CliRunner()


def canned_response(fixture_dir: Path, name: str = "synthesis_response.json") -> str:
    raw = (fixture_dir / name).read_text(encoding="utf-8")
    return json.dumps(json.loads(raw))


def fake_synthesis(fixture_dir: Path, label: str) -> tuple[CaseFile, SynthesisResult]:
    casefile = load_casefile(fixture_dir)
    provider = FakeModelProvider([canned_response(fixture_dir)])
    result = synthesize(casefile, provider, provider_name="fake", model=label)
    return casefile, result


def ollama_reply(content: str) -> httpx.Response:
    return httpx.Response(
        200,
        json={
            "model": "fake-model:1b",
            "message": {"role": "assistant", "content": content},
            "done": True,
        },
    )


def claim_texts(casefile: CaseFile) -> tuple[str, ...]:
    return tuple(claim.text for claim in casefile.claims)


# -- amber: the claims-free AMBER, preserved from weekend 2 ---------------------


def test_amber_candidates_are_a1_and_a2() -> None:
    casefile = load_casefile(AMBER_DIR)
    assert [c.id for c in detect_candidates(casefile)] == ["A1", "A2"]


def test_amber_planted_signals_are_present() -> None:
    casefile = load_casefile(AMBER_DIR)
    ids = {f.id: f for f in casefile.findings}
    assert ids["REG-003"].severity == "amber"  # accounts overdue (A1)
    assert ids["REG-009"].severity == "amber"  # wholesale churn (A2)
    assert "1 outstanding" in ids["REG-006"].statement  # the outstanding charge
    assert "nearest candidate scored 0.55" in ids["SAN-001"].statement  # near-miss
    assert casefile.media is not None
    assert len(casefile.media.items) == 3
    assert casefile.sanctions is not None
    assert casefile.sanctions.threshold == 0.7
    # Claims-free by input: no deck, no site, and the skip is explicit.
    assert casefile.claims == []
    assert casefile.claims_extraction is not None
    assert casefile.claims_extraction.performed is False
    assert "EXT-000" in ids


def test_amber_enforced_verdict_is_amber_citing_a1_a2(respx_mock: respx.MockRouter) -> None:
    _casefile, result = fake_synthesis(AMBER_DIR, "canned-amber")
    assert result.verdict.level == "amber"
    assert {"A1", "A2"} <= set(result.verdict.triggered)


def test_amber_memo_matches_the_snapshot(respx_mock: respx.MockRouter) -> None:
    casefile, result = fake_synthesis(AMBER_DIR, "canned-amber")
    memo = render_memo(apply_synthesis(casefile, result))
    assert memo.encode("utf-8") == (AMBER_DIR / "memo.md").read_bytes()


def test_amber_memo_is_language_gate_clean() -> None:
    assert find_banned_terms((AMBER_DIR / "memo.md").read_text(encoding="utf-8")) == []


def test_amber_headline_reaches_input_but_never_the_memo(
    respx_mock: respx.MockRouter,
) -> None:
    casefile = load_casefile(AMBER_DIR)
    loaded_title = synthetic.AMBER_MEDIA_ITEMS[0]["title"]
    assert "fraud" in loaded_title
    payload = build_synthesis_input(casefile, detect_candidates(casefile))
    assert casefile.media is not None
    assert loaded_title in [i["title"] for i in payload["media"]["items"]]
    memo = (AMBER_DIR / "memo.md").read_text(encoding="utf-8")
    assert loaded_title not in memo
    assert "fictional-gazette.example" in memo  # the source is still traceable


# -- golden: the RED case, claims present, R4 fired -----------------------------


def test_golden_casefile_carries_claims_assessments_and_red_verdict() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    assert [c.id for c in casefile.claims] == [f"CLM-{n:03d}" for n in range(1, 6)]
    assert [c.checkable for c in casefile.claims] == [True, True, False, True, False]
    assert casefile.claims_extraction is not None
    assert casefile.claims_extraction.performed is True
    assert casefile.claims_extraction.deck_file == "deck_fabricated_widgets.pdf"
    assert casefile.claims_extraction.deck_sha256 is not None
    assert casefile.claims_extraction.sources == ["deck p.1", "deck p.2", "deck p.3"]
    # Only checkable claims carry assessments; the two contradictions carry
    # evidence copied from the cited findings.
    by_id = {a.claim_id: a for a in casefile.assessments}
    assert set(by_id) == {"CLM-001", "CLM-002", "CLM-004"}
    assert by_id["CLM-001"].status == "contradicted"
    assert by_id["CLM-001"].basis, "contradicted without resolved evidence cannot survive"
    assert by_id["CLM-002"].status == "contradicted"
    assert by_id["CLM-004"].status == "unverified"
    assert casefile.verdict is not None
    assert casefile.verdict.level == "red"
    assert casefile.verdict.triggered == ["R4", "A1", "A2", "A4"]
    assert casefile.synthesis is not None
    assert casefile.synthesis.enforcement_notes == []


def test_golden_planted_contradictions_match_the_registry() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    assert casefile.subject.date_of_creation is not None
    assert casefile.subject.date_of_creation.isoformat() == "2019-05-14"
    assert "Operating since 2015" in casefile.claims[0].text
    assert "debt free" in casefile.claims[1].text
    outstanding = [c for c in casefile.charges if c.status == "outstanding"]
    assert len(outstanding) == 1


def test_golden_memo_carries_the_claims_table() -> None:
    memo = (GOLDEN_DIR / "memo.md").read_text(encoding="utf-8")
    assert "## Claims vs evidence" in memo
    assert "| # | Claim (source) | Public record | Status |" in memo
    assert "Contradicted" in memo
    assert "not checkable" in memo
    assert "Unverified" in memo
    assert "**RED**" in memo
    assert "**R4** (RED)" in memo


# -- the quoted-data exemption: all three directions at memo level ---------------


def test_direction_one_deck_quote_with_banned_word_renders_and_passes() -> None:
    """The golden memo quotes a deck claim containing banned vocabulary; the
    stored claim texts exempt exactly that span and nothing else."""
    casefile = load_casefile(GOLDEN_DIR)
    memo = (GOLDEN_DIR / "memo.md").read_text(encoding="utf-8")
    quoted = "Our platform eliminates fraud in widget procurement"
    assert quoted in [c.text for c in casefile.claims]
    assert quoted in memo  # the quote really renders in the table
    assert find_banned_terms(memo) == ["fraud"]  # without the exemption: a hit
    assert find_banned_terms(memo, claim_texts(casefile)) == []  # with it: clean


def test_direction_two_same_word_in_model_prose_fails() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    poisoned = casefile.model_copy(
        update={"narrative": "This one is a fraud, whatever the deck says."}
    )
    memo = render_memo(poisoned)
    assert "fraud" in find_banned_terms(memo, claim_texts(poisoned))


def test_direction_three_same_word_in_a_record_note_fails() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    assessments = [a.model_copy(deep=True) for a in casefile.assessments]
    assessments[0] = assessments[0].model_copy(
        update={"record_note": "The registry exposes the fraud here."}
    )
    poisoned = casefile.model_copy(update={"assessments": assessments})
    memo = render_memo(poisoned)
    assert "fraud" in find_banned_terms(memo, claim_texts(poisoned))


# -- green: GREEN with a supported claim ----------------------------------------


def test_green_has_no_candidates_and_clean_signals() -> None:
    casefile = load_casefile(GREEN_DIR)
    assert detect_candidates(casefile) == []
    ids = {f.id: f for f in casefile.findings}
    assert ids["REG-009"].severity == "info"
    assert "No charges are registered" in ids["REG-006"].statement
    assert casefile.media is not None and casefile.media.items == []
    assert "MED-006" in ids  # explicit zero-results absence finding
    san_statements = [f.statement for f in casefile.findings if f.stage == "sanctions"]
    assert san_statements
    assert all("No sanctions match at or above threshold 0.7" in s for s in san_statements)


def test_green_casefile_carries_a_supported_claim_and_stays_green() -> None:
    casefile = load_casefile(GREEN_DIR)
    assert [c.id for c in casefile.claims] == ["CLM-001", "CLM-002"]
    assert casefile.claims[0].checkable is True
    assert casefile.claims[1].checkable is False
    assert casefile.claims_extraction is not None
    assert casefile.claims_extraction.performed is True
    assert casefile.claims_extraction.site_url == synthetic.GREEN_SITE_URL
    assert casefile.claims_extraction.sources == ["site /", "site /about"]
    assert len(casefile.assessments) == 1
    supported = casefile.assessments[0]
    assert supported.claim_id == "CLM-001"
    assert supported.status == "supported"
    assert supported.basis
    assert casefile.verdict is not None
    assert casefile.verdict.level == "green"
    assert casefile.verdict.triggered == []


def test_green_memo_carries_the_supported_row() -> None:
    memo = (GREEN_DIR / "memo.md").read_text(encoding="utf-8")
    assert "## Claims vs evidence" in memo
    assert '| 1 | "Founded in 2018 by Mabel Meridian" (site /about) |' in memo
    assert "| Supported |" in memo
    puffery_row = (
        '| 2 | "Calm, dependable advice for ambitious teams" (site /) |  | not checkable |'
    )
    assert puffery_row in memo
    assert "**GREEN**" in memo


def test_green_memo_is_language_gate_clean() -> None:
    assert find_banned_terms((GREEN_DIR / "memo.md").read_text(encoding="utf-8")) == []


# -- the enforcement ceiling against these casefiles ----------------------------


def test_hallucinated_r1_on_amber_yields_amber_with_rejection_note() -> None:
    casefile = load_casefile(AMBER_DIR)
    provider = FakeModelProvider([synthesis_json("red", ["R1", "A1", "A2"])])
    result = synthesize(casefile, provider, provider_name="fake", model="fabricator")
    assert result.verdict.level == "amber"
    assert result.verdict.triggered == ["A1", "A2"]
    notes = result.metadata.enforcement_notes
    assert "rejected trigger R1: not supported by the casefile evidence" in notes


def test_r5_on_green_yields_green_with_rejection_note() -> None:
    """The green company has no co-appointment overlap, so R5 is rejected."""
    casefile = load_casefile(GREEN_DIR)
    provider = FakeModelProvider([synthesis_json("red", ["R5"])])
    result = synthesize(casefile, provider, provider_name="fake", model="fabricator")
    assert result.verdict.level == "green"
    assert result.verdict.triggered == []
    notes = result.metadata.enforcement_notes
    assert "rejected trigger R5: no co-appointment overlap is recorded in this casefile" in notes


def test_r5_on_golden_is_accepted_because_overlap_exists() -> None:
    """The golden company shares one other company across two current
    officers (NET-002), so a model-cited R5 clears the gate."""
    casefile = load_casefile(GOLDEN_DIR)
    assert casefile.network is not None and casefile.network.overlaps
    provider = FakeModelProvider([synthesis_json("red", ["R5", "A1", "A2"])])
    result = synthesize(casefile, provider, provider_name="fake", model="citer")
    assert result.verdict.level == "red"
    assert "R5" in result.verdict.triggered


def test_r4_on_amber_is_rejected_because_no_claims_exist() -> None:
    casefile = load_casefile(AMBER_DIR)
    provider = FakeModelProvider([synthesis_json("red", ["R4", "A1", "A2"])])
    result = synthesize(casefile, provider, provider_name="fake", model="fabricator")
    assert result.verdict.level == "amber"
    notes = result.metadata.enforcement_notes
    assert (
        "rejected trigger R4: no claim assessment survives as contradicted"
        " with resolved evidence" in notes
    )


def test_a3_a4_a5_on_amber_are_rejected_without_claims() -> None:
    casefile = load_casefile(AMBER_DIR)
    provider = FakeModelProvider([synthesis_json("amber", ["A1", "A2", "A3", "A4", "A5"])])
    result = synthesize(casefile, provider, provider_name="fake", model="fabricator")
    assert result.verdict.level == "amber"
    assert result.verdict.triggered == ["A1", "A2"]
    notes = " ".join(result.metadata.enforcement_notes)
    assert "rejected trigger A3: no checkable claims are recorded" in notes
    assert "rejected trigger A4: no model-assessed checkable claim survives" in notes
    assert "rejected trigger A5: no checkable claims are recorded" in notes


def test_a3_and_a5_on_golden_are_accepted_because_claims_exist() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    provider = FakeModelProvider([synthesis_json("amber", ["A1", "A2", "A3", "A5"])])
    result = synthesize(casefile, provider, provider_name="fake", model="citer")
    assert result.verdict.level == "amber"
    assert result.verdict.triggered == ["A1", "A2", "A3", "A5"]


@pytest.mark.parametrize(
    ("level", "triggered"),
    [
        ("green", []),
        ("amber", ["A1", "A2"]),
        ("red", ["R1", "A1", "A2"]),
        ("red", ["R3", "R4", "R5"]),
        ("red", ["r2"]),
    ],
)
def test_amber_level_is_anchored_against_fabricated_reds(level: str, triggered: list[str]) -> None:
    """Same claims-free casefile, same level, no matter what the model invents.

    R5 appears in one behavior set and is rejected here: the amber casefile
    has no co-appointment overlap.
    """
    casefile = load_casefile(AMBER_DIR)
    assert casefile.network is not None and casefile.network.overlaps == []
    provider = FakeModelProvider([synthesis_json(level, triggered)])
    result = synthesize(casefile, provider, provider_name="fake", model="anchor-probe")
    assert result.verdict.level == "amber"


@pytest.mark.parametrize(
    ("level", "triggered"),
    [
        ("green", []),
        ("red", ["R1"]),
        ("red", ["R4"]),
        ("red", ["r5"]),
    ],
)
def test_green_level_is_anchored_against_fabricated_reds(level: str, triggered: list[str]) -> None:
    casefile = load_casefile(GREEN_DIR)
    provider = FakeModelProvider([synthesis_json(level, triggered)])
    result = synthesize(casefile, provider, provider_name="fake", model="anchor-probe")
    assert result.verdict.level == "green"


GOLDEN_CONTRADICTED = [
    assessment_json(
        "CLM-001", "contradicted", ["REG-002"], "Incorporated on 2019-05-14 per the registry."
    ),
    assessment_json("CLM-002", "contradicted", ["REG-006"], "One charge is outstanding."),
    assessment_json("CLM-004", "unverified", [], "No public headcount source."),
]


@pytest.mark.parametrize(
    ("level", "triggered"),
    [
        ("red", ["R4", "A1", "A2"]),
        ("red", ["R4", "R1", "R3", "A1", "A2"]),  # fabricated reds die, R4 stands
        ("green", ["r4"]),  # wrong level and casing, same enforced outcome
    ],
)
def test_golden_is_red_whenever_the_surviving_contradiction_is_cited(
    level: str, triggered: list[str]
) -> None:
    casefile = load_casefile(GOLDEN_DIR)
    response = synthesis_json(level, triggered, assessments=GOLDEN_CONTRADICTED)
    provider = FakeModelProvider([response])
    result = synthesize(casefile, provider, provider_name="fake", model="anchor-probe")
    assert result.verdict.level == "red"
    assert "R4" in result.verdict.triggered


@pytest.mark.parametrize(
    ("level", "triggered"),
    [
        ("green", []),
        ("red", ["R1"]),
        ("red", ["R4"]),  # cited, but no contradiction survives the downgrade
    ],
)
def test_golden_floor_holds_at_amber_when_no_contradiction_survives(
    level: str, triggered: list[str]
) -> None:
    """Without a surviving contradicted assessment the mechanical floor
    (A1, A2) still holds and no fabricated red can lift the level."""
    casefile = load_casefile(GOLDEN_DIR)
    unresolvable = [
        assessment_json("CLM-001", "contradicted", ["ZZZ-001"], "Note."),
        assessment_json("CLM-002", "unverified", [], "Note."),
        assessment_json("CLM-004", "unverified", [], "Note."),
    ]
    provider = FakeModelProvider([synthesis_json(level, triggered, assessments=unresolvable)])
    result = synthesize(casefile, provider, provider_name="fake", model="anchor-probe")
    assert result.verdict.level == "amber"
    assert {"A1", "A2"} <= set(result.verdict.triggered)
    assert "R4" not in result.verdict.triggered


def test_adversarial_trigger_ids_never_reach_the_memo() -> None:
    """Markdown, URLs, banned words, and an em dash inside fake trigger ids
    must leave no trace in the rendered memo: notes are count-only."""
    casefile = load_casefile(AMBER_DIR)
    em_dash = "\u2014"
    hostile = [
        "[R1](https://evil.example/fraud)",
        "R1 fraud injection",
        f"R9{em_dash}sneaky",
        "**bold** `markdown`",
    ]
    provider = FakeModelProvider([synthesis_json("red", [*hostile, "A1", "A2"])])
    result = synthesize(casefile, provider, provider_name="fake", model="hostile")
    memo = render_memo(apply_synthesis(casefile, result))
    for fragment in (
        "evil.example",
        "fraud",
        em_dash,
        "**bold**",
        "`markdown`",
        "sneaky",
        "[R1]",
    ):
        assert fragment not in memo
    assert find_banned_terms(memo) == []
    assert "dropped 4 unrecognized trigger id(s)" in memo
    assert result.verdict.level == "amber"


# -- full pipeline replay: fixture drift guards ---------------------------------


@pytest.fixture
def replay_env(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("COMPANIES_HOUSE_API_KEY", "fixture-key-0123456789-not-a-real-key")
    monkeypatch.setenv("COLDSCREEN_SCREENED_AT", "2026-08-18T12:00:00+00:00")
    monkeypatch.setenv("COLDSCREEN_CACHE_DIR", str(tmp_path / "cache"))
    return tmp_path


def assert_no_key_reaches_disk(root: Path) -> None:
    for path in root.rglob("*"):
        if path.is_file():
            content = path.read_bytes()
            assert synthetic.SANCTIONS_TEST_KEY.encode() not in content, path
            assert synthetic.TAVILY_TEST_KEY.encode() not in content, path


def test_amber_casefile_replays_byte_identically(
    replay_env: Path, respx_mock: respx.MockRouter, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("OPENSANCTIONS_API_KEY", synthetic.SANCTIONS_TEST_KEY)
    monkeypatch.setenv("TAVILY_API_KEY", synthetic.TAVILY_TEST_KEY)
    synthetic.register_amber_routes(respx_mock)
    result = runner.invoke(app, ["screen", synthetic.AMBER_NUMBER])
    assert result.exit_code == 0, result.output
    produced = (
        replay_env / "cases" / "gilded-anvil-holdings-ltd-99999901" / "casefile.json"
    ).read_bytes()
    assert produced == (AMBER_DIR / "casefile.json").read_bytes()
    assert_no_key_reaches_disk(replay_env)


def test_golden_case_replays_byte_identically_with_deck_and_model(
    replay_env: Path, respx_mock: respx.MockRouter, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The offline demo: fixture company plus fixture deck through the
    canned model produces the RED golden memo with the claims table,
    byte-stably. Exactly two model calls: claims extraction, synthesis."""
    monkeypatch.setenv("COLDSCREEN_MODEL", "ollama:fake-model:1b")
    mock_company_routes(respx_mock)
    route = respx_mock.post(OLLAMA_CHAT_URL).mock(
        side_effect=[
            ollama_reply(canned_response(GOLDEN_DIR, "claims_response.json")),
            ollama_reply(canned_response(GOLDEN_DIR, "synthesis_response.json")),
        ]
    )
    result = runner.invoke(app, ["screen", "99999999", "--deck", str(DECK_PATH)])
    assert result.exit_code == 0, result.output
    assert route.call_count == 2
    case_dir = replay_env / "cases" / "fabricated-widgets-ltd-99999999"
    assert (case_dir / "casefile.json").read_bytes() == (GOLDEN_DIR / "casefile.json").read_bytes()
    assert (case_dir / "memo.md").read_bytes() == (GOLDEN_DIR / "memo.md").read_bytes()
    # The deck evidence is text plus provenance, never the binary.
    deck_evidence = json.loads(
        (case_dir / "evidence" / "deck_text.json").read_text(encoding="utf-8")
    )
    assert deck_evidence["body"]["kind"] == "deck_text"
    assert deck_evidence["body"]["sha256"]
    assert "%PDF" not in json.dumps(deck_evidence)


def test_green_case_replays_byte_identically_with_site_and_model(
    replay_env: Path, respx_mock: respx.MockRouter, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("COLDSCREEN_MODEL", "ollama:fake-model:1b")
    monkeypatch.setenv("OPENSANCTIONS_API_KEY", synthetic.SANCTIONS_TEST_KEY)
    monkeypatch.setenv("TAVILY_API_KEY", synthetic.TAVILY_TEST_KEY)
    synthetic.register_green_routes(respx_mock)
    respx_mock.post(OLLAMA_CHAT_URL).mock(
        side_effect=[
            ollama_reply(canned_response(GREEN_DIR, "claims_response.json")),
            ollama_reply(canned_response(GREEN_DIR, "synthesis_response.json")),
        ]
    )
    result = runner.invoke(
        app, ["screen", synthetic.GREEN_NUMBER, "--site", synthetic.GREEN_SITE_URL]
    )
    assert result.exit_code == 0, result.output
    case_dir = replay_env / "cases" / "placid-meridian-consulting-ltd-99999902"
    assert (case_dir / "casefile.json").read_bytes() == (GREEN_DIR / "casefile.json").read_bytes()
    assert (case_dir / "memo.md").read_bytes() == (GREEN_DIR / "memo.md").read_bytes()
    assert_no_key_reaches_disk(replay_env)


def test_rerun_reassesses_stored_claims_without_reextracting(
    replay_env: Path, respx_mock: respx.MockRouter, monkeypatch: pytest.MonkeyPatch
) -> None:
    """rerun on the golden case makes exactly ONE model call (synthesis with
    the claim-id-constrained schema), never a claims extraction call, and
    reproduces the RED verdict from the STORED claims."""
    case_dir = replay_env / "case-golden"
    case_dir.mkdir()
    shutil.copyfile(GOLDEN_DIR / "casefile.json", case_dir / "casefile.json")
    route = respx_mock.post(OLLAMA_CHAT_URL).mock(
        side_effect=[ollama_reply(canned_response(GOLDEN_DIR, "synthesis_response.json"))]
    )
    result = runner.invoke(app, ["rerun", str(case_dir), "--model", "ollama:fake-model:1b"])
    assert result.exit_code == 0, result.output
    assert route.call_count == 1
    sent = json.loads(route.calls.last.request.content.decode("utf-8"))
    claim_id_schema = sent["format"]["properties"]["assessments"]["items"]["properties"]["claim_id"]
    assert claim_id_schema["enum"] == ["CLM-001", "CLM-002", "CLM-004"]
    casefile = CaseFile.model_validate_json(
        (case_dir / "casefile.json").read_text(encoding="utf-8")
    )
    assert casefile.verdict is not None
    assert casefile.verdict.level == "red"
    assert "R4" in casefile.verdict.triggered
    memo = (case_dir / "memo.md").read_text(encoding="utf-8")
    assert "## Claims vs evidence" in memo
