"""Golden AMBER and green GREEN cases: snapshots, enforcement, drift guards.

The committed casefiles were generated by running the real CLI against the
synthetic routes in tests/synthetic.py with a frozen clock. The replay tests
re-run that pipeline and require byte-identical casefiles, so any behavior
drift in the deterministic stages shows up as a fixture diff, not silence.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import respx
from typer.testing import CliRunner

from firstpass.casedir import load_casefile
from firstpass.cli import app
from firstpass.language import find_banned_terms
from firstpass.models import CaseFile
from firstpass.render import render_memo
from firstpass.rubric import detect_candidates
from firstpass.synthesis import (
    SynthesisResult,
    apply_synthesis,
    build_synthesis_input,
    synthesize,
)

from . import synthetic
from .conftest import FIXTURES_DIR
from .fakes import FakeModelProvider, synthesis_json

GOLDEN_DIR = FIXTURES_DIR / "golden"
GREEN_DIR = FIXTURES_DIR / "green"

runner = CliRunner()


def canned_response(fixture_dir: Path) -> str:
    raw = (fixture_dir / "synthesis_response.json").read_text(encoding="utf-8")
    return json.dumps(json.loads(raw))


def fake_synthesis(fixture_dir: Path, label: str) -> tuple[CaseFile, SynthesisResult]:
    casefile = load_casefile(fixture_dir)
    provider = FakeModelProvider([canned_response(fixture_dir)])
    result = synthesize(casefile, provider, provider_name="fake", model=label)
    return casefile, result


# -- golden: AMBER ------------------------------------------------------------


def test_golden_candidates_are_a1_and_a2() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    assert [c.id for c in detect_candidates(casefile)] == ["A1", "A2"]


def test_golden_planted_signals_are_present() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    ids = {f.id: f for f in casefile.findings}
    assert ids["REG-003"].severity == "amber"  # accounts overdue (A1)
    assert ids["REG-009"].severity == "amber"  # wholesale churn (A2)
    assert "1 outstanding" in ids["REG-006"].statement  # the outstanding charge
    assert "nearest candidate scored 0.55" in ids["SAN-001"].statement  # near-miss
    assert casefile.media is not None
    assert len(casefile.media.items) == 3
    assert casefile.sanctions is not None
    assert casefile.sanctions.threshold == 0.7


def test_golden_enforced_verdict_is_amber_citing_a1_a2(respx_mock: respx.MockRouter) -> None:
    _casefile, result = fake_synthesis(GOLDEN_DIR, "canned-golden")
    assert result.verdict.level == "amber"
    assert {"A1", "A2"} <= set(result.verdict.triggered)


def test_golden_memo_matches_the_snapshot(respx_mock: respx.MockRouter) -> None:
    casefile, result = fake_synthesis(GOLDEN_DIR, "canned-golden")
    memo = render_memo(apply_synthesis(casefile, result))
    assert memo.encode("utf-8") == (GOLDEN_DIR / "memo.md").read_bytes()


def test_golden_memo_is_language_gate_clean() -> None:
    assert find_banned_terms((GOLDEN_DIR / "memo.md").read_text(encoding="utf-8")) == []


def test_golden_headline_reaches_input_but_never_the_memo(
    respx_mock: respx.MockRouter,
) -> None:
    casefile = load_casefile(GOLDEN_DIR)
    loaded_title = synthetic.GOLDEN_MEDIA_ITEMS[0]["title"]
    assert "fraud" in loaded_title
    payload = build_synthesis_input(casefile, detect_candidates(casefile))
    assert casefile.media is not None
    assert loaded_title in [i["title"] for i in payload["media"]["items"]]
    memo = (GOLDEN_DIR / "memo.md").read_text(encoding="utf-8")
    assert loaded_title not in memo
    assert "fictional-gazette.example" in memo  # the source is still traceable


# -- green: GREEN --------------------------------------------------------------


def test_green_has_no_candidates_and_clean_signals() -> None:
    casefile = load_casefile(GREEN_DIR)
    assert detect_candidates(casefile) == []
    ids = {f.id: f for f in casefile.findings}
    assert ids["REG-009"].severity == "info"
    assert "No charges are registered" in ids["REG-006"].statement
    assert casefile.media is not None and casefile.media.items == []
    assert "MED-006" in ids  # explicit zero-results absence finding
    san_statements = [f.statement for f in casefile.findings if f.stage == "sanctions"]
    assert san_statements
    assert all("No sanctions match at or above threshold 0.7" in s for s in san_statements)


def test_green_enforced_verdict_is_green_citing_nothing(respx_mock: respx.MockRouter) -> None:
    _casefile, result = fake_synthesis(GREEN_DIR, "canned-green")
    assert result.verdict.level == "green"
    assert result.verdict.triggered == []
    assert result.verdict_enforcement is None


def test_green_memo_matches_the_snapshot(respx_mock: respx.MockRouter) -> None:
    casefile, result = fake_synthesis(GREEN_DIR, "canned-green")
    memo = render_memo(apply_synthesis(casefile, result))
    assert memo.encode("utf-8") == (GREEN_DIR / "memo.md").read_bytes()


def test_green_memo_is_language_gate_clean() -> None:
    assert find_banned_terms((GREEN_DIR / "memo.md").read_text(encoding="utf-8")) == []


# -- the enforcement ceiling against these casefiles ----------------------------


def test_hallucinated_r1_on_golden_yields_amber_with_rejection_note() -> None:
    casefile = load_casefile(GOLDEN_DIR)
    provider = FakeModelProvider([synthesis_json("red", ["R1", "A1", "A2"])])
    result = synthesize(casefile, provider, provider_name="fake", model="fabricator")
    assert result.verdict.level == "amber"
    assert result.verdict.triggered == ["A1", "A2"]
    notes = result.metadata.enforcement_notes
    assert "rejected trigger R1: not supported by the casefile evidence" in notes


def test_r5_on_green_yields_green_with_rejection_note() -> None:
    casefile = load_casefile(GREEN_DIR)
    provider = FakeModelProvider([synthesis_json("red", ["R5"])])
    result = synthesize(casefile, provider, provider_name="fake", model="fabricator")
    assert result.verdict.level == "green"
    assert result.verdict.triggered == []
    notes = result.metadata.enforcement_notes
    assert (
        "rejected trigger R5: requires the claims layer which is not part of this milestone"
        in notes
    )


@pytest.mark.parametrize(
    ("level", "triggered"),
    [
        ("green", []),
        ("amber", ["A1", "A2"]),
        ("red", ["R1", "A1", "A2"]),
        ("red", ["R3", "R4", "R5"]),
        ("red", ["r2"]),
    ],
)
def test_golden_level_is_anchored_against_fabricated_reds(level: str, triggered: list[str]) -> None:
    """Same casefile, same level, no matter what Rs the model invents."""
    casefile = load_casefile(GOLDEN_DIR)
    provider = FakeModelProvider([synthesis_json(level, triggered)])
    result = synthesize(casefile, provider, provider_name="fake", model="anchor-probe")
    assert result.verdict.level == "amber"


@pytest.mark.parametrize(
    ("level", "triggered"),
    [
        ("green", []),
        ("red", ["R1"]),
        ("red", ["R4"]),
        ("red", ["r5"]),
    ],
)
def test_green_level_is_anchored_against_fabricated_reds(level: str, triggered: list[str]) -> None:
    casefile = load_casefile(GREEN_DIR)
    provider = FakeModelProvider([synthesis_json(level, triggered)])
    result = synthesize(casefile, provider, provider_name="fake", model="anchor-probe")
    assert result.verdict.level == "green"


def test_adversarial_trigger_ids_never_reach_the_memo() -> None:
    """Markdown, URLs, banned words, and an em dash inside fake trigger ids
    must leave no trace in the rendered memo: notes are count-only."""
    casefile = load_casefile(GOLDEN_DIR)
    em_dash = "\u2014"
    hostile = [
        "[R1](https://evil.example/fraud)",
        "R1 fraud injection",
        f"R9{em_dash}sneaky",
        "**bold** `markdown`",
    ]
    provider = FakeModelProvider([synthesis_json("red", [*hostile, "A1", "A2"])])
    result = synthesize(casefile, provider, provider_name="fake", model="hostile")
    memo = render_memo(apply_synthesis(casefile, result))
    for fragment in (
        "evil.example",
        "fraud",
        em_dash,
        "**bold**",
        "`markdown`",
        "sneaky",
        "[R1]",
    ):
        assert fragment not in memo
    assert find_banned_terms(memo) == []
    assert "dropped 4 unrecognized trigger id(s)" in memo
    assert result.verdict.level == "amber"


# -- full pipeline replay: fixture drift guards ---------------------------------


@pytest.fixture
def replay_env(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("COMPANIES_HOUSE_API_KEY", "fixture-key-0123456789-not-a-real-key")
    monkeypatch.setenv("FIRSTPASS_SCREENED_AT", "2026-08-18T12:00:00+00:00")
    monkeypatch.setenv("FIRSTPASS_CACHE_DIR", str(tmp_path / "cache"))
    monkeypatch.setenv("OPENSANCTIONS_API_KEY", synthetic.SANCTIONS_TEST_KEY)
    monkeypatch.setenv("TAVILY_API_KEY", synthetic.TAVILY_TEST_KEY)
    return tmp_path


def test_golden_casefile_replays_byte_identically(
    replay_env: Path, respx_mock: respx.MockRouter
) -> None:
    synthetic.register_golden_routes(respx_mock)
    result = runner.invoke(app, ["screen", synthetic.GOLDEN_NUMBER])
    assert result.exit_code == 0, result.output
    produced = (
        replay_env / "cases" / "gilded-anvil-holdings-ltd-99999901" / "casefile.json"
    ).read_bytes()
    assert produced == (GOLDEN_DIR / "casefile.json").read_bytes()
    # Neither the OpenSanctions key nor the Tavily key may reach any file.
    for path in replay_env.rglob("*"):
        if path.is_file():
            content = path.read_bytes()
            assert synthetic.SANCTIONS_TEST_KEY.encode() not in content, path
            assert synthetic.TAVILY_TEST_KEY.encode() not in content, path


def test_green_casefile_replays_byte_identically(
    replay_env: Path, respx_mock: respx.MockRouter
) -> None:
    synthetic.register_green_routes(respx_mock)
    result = runner.invoke(app, ["screen", synthetic.GREEN_NUMBER])
    assert result.exit_code == 0, result.output
    produced = (
        replay_env / "cases" / "placid-meridian-consulting-ltd-99999902" / "casefile.json"
    ).read_bytes()
    assert produced == (GREEN_DIR / "casefile.json").read_bytes()
